# fly.toml app configuration file generated for zene-org-late-bird-2326 on 2024-10-10T18:47:19+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zene-org-late-bird-2326'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
